/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guesstheword.gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Arsalan Fakhar
 */
public class filingpanel extends javax.swing.JFrame {

    File f=new File("src\\files\\filing.txt");
    //getClass().getResource("/files/filing.txt").getFile()
    public filingpanel() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainreg = new javax.swing.JButton();
        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        mainlogbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passtxt = new javax.swing.JTextField();
        Emailtxt = new javax.swing.JTextField();
        ustxt = new javax.swing.JTextField();
        regisbut = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginpanel.setBackground(new java.awt.Color(55, 196, 206));
        loginpanel.setForeground(new java.awt.Color(255, 255, 255));
        loginpanel.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ｕｓｅｒｎａｍｅ 臆穏ド");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        loginpanel.add(jLabel1);
        jLabel1.setBounds(140, 110, 140, 20);

        jLabel2.setBackground(jLabel1.getBackground());
        jLabel2.setForeground(jLabel1.getForeground());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ｐａｓｓｗｏｒｄ　鬱る仮");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        loginpanel.add(jLabel2);
        jLabel2.setBounds(140, 180, 150, 20);

        mainreg.setBackground(new java.awt.Color(0, 0, 0));
        mainreg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mainreg.setForeground(new java.awt.Color(255, 255, 255));
        mainreg.setText("Sign Up");
        mainreg.setBorder(mainlogbtn.getBorder());
        mainreg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainregActionPerformed(evt);
            }
        });
        loginpanel.add(mainreg);
        mainreg.setBounds(260, 350, 80, 30);

        usernametxt.setFont(new java.awt.Font("Eras Demi ITC", 2, 12)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(153, 153, 153));
        usernametxt.setText("Enter username");
        usernametxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernametxtMouseClicked(evt);
            }
        });
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        usernametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernametxtFocusGained(evt);
            }
        });
        loginpanel.add(usernametxt);
        usernametxt.setBounds(140, 140, 320, 30);

        passwordtxt.setFont(usernametxt.getFont());
        passwordtxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordtxt.setText("Enter password");
        passwordtxt.setName(""); // NOI18N
        passwordtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordtxtMouseClicked(evt);
            }
        });
        passwordtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordtxtFocusGained(evt);
            }
        });
        loginpanel.add(passwordtxt);
        passwordtxt.setBounds(140, 210, 320, 30);

        mainlogbtn.setBackground(new java.awt.Color(115, 29, 144));
        mainlogbtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        mainlogbtn.setForeground(new java.awt.Color(255, 255, 255));
        mainlogbtn.setText("Login");
        mainlogbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainlogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainlogbtnActionPerformed(evt);
            }
        });
        loginpanel.add(mainlogbtn);
        mainlogbtn.setBounds(240, 260, 120, 36);

        jLabel4.setBackground(getBackground());
        jLabel4.setFont(new java.awt.Font("Minion Pro Med", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login");
        jLabel4.setAlignmentX(0.5F);
        loginpanel.add(jLabel4);
        jLabel4.setBounds(270, 40, 50, 19);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("OR if you don't have an account yet...");
        loginpanel.add(jLabel14);
        jLabel14.setBounds(180, 320, 250, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        jLabel13.setText("bg");
        loginpanel.add(jLabel13);
        jLabel13.setBounds(-20, -30, 2100, 1100);

        getContentPane().add(loginpanel, "card2");

        RegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nametxt.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 12)); // NOI18N
        nametxt.setForeground(new java.awt.Color(153, 153, 153));
        nametxt.setText("Full Name");
        nametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nametxtMouseClicked(evt);
            }
        });
        RegisterPanel.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 270, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Not a Member? Sign Up!");
        RegisterPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 224, 50));

        passtxt.setBackground(nametxt.getBackground());
        passtxt.setFont(nametxt.getFont());
        passtxt.setForeground(nametxt.getForeground());
        passtxt.setText("Password");
        passtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passtxtMouseClicked(evt);
            }
        });
        RegisterPanel.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 270, 30));

        Emailtxt.setBackground(nametxt.getBackground());
        Emailtxt.setFont(nametxt.getFont());
        Emailtxt.setForeground(nametxt.getForeground());
        Emailtxt.setText("Email Address");
        Emailtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailtxtMouseClicked(evt);
            }
        });
        RegisterPanel.add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 270, 30));

        ustxt.setBackground(nametxt.getBackground());
        ustxt.setFont(nametxt.getFont());
        ustxt.setForeground(nametxt.getForeground());
        ustxt.setText("Username");
        ustxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ustxtMouseClicked(evt);
            }
        });
        ustxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ustxtActionPerformed(evt);
            }
        });
        RegisterPanel.add(ustxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 270, 30));

        regisbut.setBackground(new java.awt.Color(76, 144, 32));
        regisbut.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        regisbut.setForeground(new java.awt.Color(255, 255, 255));
        regisbut.setText("Sign Up!");
        regisbut.setBorder(new javax.swing.border.LineBorder(jLabel9.getBackground(), 1, true));
        regisbut.setBorderPainted(false);
        regisbut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisbutActionPerformed(evt);
            }
        });
        RegisterPanel.add(regisbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, 30));

        jLabel12.setBackground(new java.awt.Color(203, 9, 9));
        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Registration");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);
        RegisterPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        jCheckBox1.setText("I Agree to Terms of Use");
        RegisterPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Void\\Desktop\\project\\login panel\\minimalism-landscape-q3.jpg")); // NOI18N
        jLabel9.setText("bg1");
        RegisterPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, 660, 420));

        getContentPane().add(RegisterPanel, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regisbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisbutActionPerformed
        try {
            System.out.println(nametxt.getText());
            if(nametxt.getText().isEmpty() || passtxt.getText().isEmpty() || ustxt.getText().isEmpty() ||nametxt.getText().trim()=="Full Name" ||passtxt.getText().trim()=="Password" ||ustxt.getText().trim()=="Username"){
                showMessageDialog(null,"Please enter all details","Alert",JOptionPane.ERROR_MESSAGE);
            }
            else{
                PrintStream write=new PrintStream(f);
                write.print("Username: ");write.println(ustxt.getText());
                write.print("Password: ");write.println(passtxt.getText());
                write.print("Name: ");write.println(nametxt.getText());
                showMessageDialog(null, "Registration sucessful","Sucess",JOptionPane.INFORMATION_MESSAGE);
                RegisterPanel.setVisible(false);
                loginpanel.setVisible(true);
            }
        } catch (FileNotFoundException ex) {
            showMessageDialog(null, "File not found","Alert",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_regisbutActionPerformed

    private void mainlogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainlogbtnActionPerformed
        try {
            Scanner read=new Scanner(f);
            if(usernametxt.getText().isEmpty() && passwordtxt.getText().isEmpty())
            {
                showMessageDialog(null, "Text field can't be left blank","Alert",JOptionPane.WARNING_MESSAGE);
            }
            else {
                read.next();
                String readus=read.nextLine();
                read.next();
                String readpass=read.nextLine();
                //to remove spaces
                readus=readus.trim();readpass=readpass.trim();
                System.out.println(readus+readpass);

                if(usernametxt.getText().trim().equalsIgnoreCase(readus) && passwordtxt.getText().trim().equalsIgnoreCase(readpass))
                {
                    showMessageDialog(null, "Login sucessful");
                    //new1 start
                    //to close the window
                    setVisible(false);
                    dispose();
                    //new1 end
                    MainPanel gamepanel=new MainPanel();
                    gamepanel.setVisible(true);

                }
                else{
                    showMessageDialog(null, "EIther username or password can't be matched","Alert",JOptionPane.WARNING_MESSAGE);

                }

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(filingpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainlogbtnActionPerformed

    private void passwordtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordtxtMouseClicked
        passwordtxt.setText(null);
    }//GEN-LAST:event_passwordtxtMouseClicked

    private void passwordtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordtxtFocusGained

    }//GEN-LAST:event_passwordtxtFocusGained

    private void usernametxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametxtFocusGained

    }//GEN-LAST:event_usernametxtFocusGained

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void usernametxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernametxtMouseClicked
        usernametxt.setText(null);
    }//GEN-LAST:event_usernametxtMouseClicked

    private void mainregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainregActionPerformed
        loginpanel.setVisible(false);
        RegisterPanel.setVisible(true);
    }//GEN-LAST:event_mainregActionPerformed

    private void ustxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ustxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ustxtActionPerformed

    private void nametxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nametxtMouseClicked
    nametxt.setText(null);
    }//GEN-LAST:event_nametxtMouseClicked

    private void ustxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ustxtMouseClicked
        ustxt.setText(null);
    }//GEN-LAST:event_ustxtMouseClicked

    private void passtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passtxtMouseClicked
        passtxt.setText(null);
    }//GEN-LAST:event_passtxtMouseClicked

    private void EmailtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailtxtMouseClicked
        Emailtxt.setText(null);
    }//GEN-LAST:event_EmailtxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filingpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filingpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filingpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filingpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filingpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JButton mainlogbtn;
    private javax.swing.JButton mainreg;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JButton regisbut;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JTextField ustxt;
    // End of variables declaration//GEN-END:variables
}
