/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guesstheword.gui;



import javax.swing.JTextField;
import levelsmenu.Code_Levels;
import java.awt.Font;
import java.awt.*;
import java.awt.font.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;

/**
 *
 * @author Arsalan Fakhar
 */
public class MainPanel extends javax.swing.JFrame {

private char difficultyoflevel;
private int currentlevelno;
private int startofwords=0;
private int endofwords=0;
JTextField[] mytextfield=new JTextField[8]; //It means 7textfields
JLabel[] mystars=new JLabel[3];
JLabel[] mylevelstars=new JLabel[30];
JButton[] mybuttons=new JButton[8];
private  ArrayList<Integer> indexes=new  ArrayList<>(); 
private char[] origch;private String origstring;
private  int  numberoftries=0;
private int[] numberofstars=new int[10];

char[] indexesofwords;
private int hintcount=0;

//new start 3 file bana lena
//nayi chize badal dena
String destination="";
File scorefile=new File(destination);
//new end

//new start

boolean gamestarted=false;

JLabel[] locks =new JLabel[10];
JPanel[] chotapanel=new JPanel[10];


//new end

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
       setResizable(false);
       shadow.setBackground(new Color(0,0,0,50));
       shadow.setVisible(false);
       
       //new start
       declarelevelstars();declarelock();declarelevelpanel();
       checkgamestate();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JPanel();
        newgame = new javax.swing.JLabel();
        resume = new javax.swing.JLabel();
        options = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectpanel = new javax.swing.JPanel();
        selectdifficuty = new javax.swing.JLabel();
        easy = new javax.swing.JLabel();
        medium = new javax.swing.JLabel();
        hard = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        levelpanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lev1 = new javax.swing.JPanel();
        level1 = new javax.swing.JLabel();
        lock1 = new javax.swing.JLabel();
        levelstar1 = new javax.swing.JLabel();
        levelstar2 = new javax.swing.JLabel();
        levelstar3 = new javax.swing.JLabel();
        lev2 = new javax.swing.JPanel();
        level2 = new javax.swing.JLabel();
        lock2 = new javax.swing.JLabel();
        levelstar4 = new javax.swing.JLabel();
        levelstar5 = new javax.swing.JLabel();
        levelstar6 = new javax.swing.JLabel();
        lev3 = new javax.swing.JPanel();
        level3 = new javax.swing.JLabel();
        lock3 = new javax.swing.JLabel();
        levelstar7 = new javax.swing.JLabel();
        levelstar8 = new javax.swing.JLabel();
        levelstar9 = new javax.swing.JLabel();
        lev4 = new javax.swing.JPanel();
        level4 = new javax.swing.JLabel();
        lock4 = new javax.swing.JLabel();
        levelstar10 = new javax.swing.JLabel();
        levelstar11 = new javax.swing.JLabel();
        levelstar12 = new javax.swing.JLabel();
        lev5 = new javax.swing.JPanel();
        level5 = new javax.swing.JLabel();
        lock5 = new javax.swing.JLabel();
        levelstar13 = new javax.swing.JLabel();
        levelstar14 = new javax.swing.JLabel();
        levelstar15 = new javax.swing.JLabel();
        lev6 = new javax.swing.JPanel();
        level6 = new javax.swing.JLabel();
        lock6 = new javax.swing.JLabel();
        levelstar16 = new javax.swing.JLabel();
        levelstar17 = new javax.swing.JLabel();
        levelstar18 = new javax.swing.JLabel();
        lev7 = new javax.swing.JPanel();
        level7 = new javax.swing.JLabel();
        lock7 = new javax.swing.JLabel();
        levelstar19 = new javax.swing.JLabel();
        levelstar20 = new javax.swing.JLabel();
        levelstar21 = new javax.swing.JLabel();
        lev8 = new javax.swing.JPanel();
        level8 = new javax.swing.JLabel();
        lock8 = new javax.swing.JLabel();
        levelstar22 = new javax.swing.JLabel();
        levelstar23 = new javax.swing.JLabel();
        levelstar24 = new javax.swing.JLabel();
        lev9 = new javax.swing.JPanel();
        level9 = new javax.swing.JLabel();
        lock9 = new javax.swing.JLabel();
        levelstar25 = new javax.swing.JLabel();
        levelstar26 = new javax.swing.JLabel();
        levelstar27 = new javax.swing.JLabel();
        lev10 = new javax.swing.JPanel();
        level10 = new javax.swing.JLabel();
        lock10 = new javax.swing.JLabel();
        levelstar28 = new javax.swing.JLabel();
        levelstar29 = new javax.swing.JLabel();
        levelstar30 = new javax.swing.JLabel();
        gotodifficultybtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        trickpanel = new javax.swing.JPanel();
        shadow = new javax.swing.JPanel();
        shadowinner = new javax.swing.JPanel();
        pause = new javax.swing.JPanel();
        trgobackbtn = new javax.swing.JLabel();
        trresumebtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        trstatus = new javax.swing.JPanel();
        statustxt = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        btnnextlevel = new javax.swing.JButton();
        btnretry = new javax.swing.JButton();
        lastpanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        hintlabel = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        trieslabel = new javax.swing.JLabel();
        lastpanelsabarkar = new javax.swing.JLabel();
        ch1 = new javax.swing.JTextField();
        ch2 = new javax.swing.JTextField();
        ch3 = new javax.swing.JTextField();
        ch4 = new javax.swing.JTextField();
        ch5 = new javax.swing.JTextField();
        ch6 = new javax.swing.JTextField();
        ch7 = new javax.swing.JTextField();
        ch8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        chalphutpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        start.setPreferredSize(new java.awt.Dimension(829, 553));
        start.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                startComponentAdded(evt);
            }
        });
        start.setLayout(null);

        newgame.setBackground(new java.awt.Color(255, 255, 255));
        newgame.setFont(new java.awt.Font("Prestige Elite Std", 1, 27)); // NOI18N
        newgame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newgame.setText("NEW GAME");
        newgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newgame.setOpaque(true);
        newgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newgameMouseClicked(evt);
            }
        });
        start.add(newgame);
        newgame.setBounds(0, 160, 128, 30);

        resume.setBackground(newgame.getBackground());
        resume.setFont(newgame.getFont());
        resume.setForeground(newgame.getForeground());
        resume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resume.setText("RESUME");
        resume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resume.setEnabled(false);
        resume.setOpaque(true);
        resume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumeMouseClicked(evt);
            }
        });
        start.add(resume);
        resume.setBounds(0, 70, 100, 30);

        options.setBackground(newgame.getBackground());
        options.setFont(newgame.getFont());
        options.setForeground(newgame.getForeground());
        options.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        options.setText("OPTIONS");
        options.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        options.setOpaque(true);
        start.add(options);
        options.setBounds(0, 260, 120, 30);

        exit.setBackground(newgame.getBackground());
        exit.setFont(newgame.getFont());
        exit.setForeground(newgame.getForeground());
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("EXIT");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setOpaque(true);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        start.add(exit);
        exit.setBounds(0, 350, 70, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SvnuN4M.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(829, 553));
        start.add(jLabel4);
        jLabel4.setBounds(-30, -20, 970, 620);

        jPanel1.add(start, "card2");

        selectpanel.setPreferredSize(new java.awt.Dimension(829, 553));
        selectpanel.setLayout(null);

        selectdifficuty.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        selectdifficuty.setForeground(new java.awt.Color(255, 255, 255));
        selectdifficuty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectdifficuty.setText("Select Difficulty");
        selectpanel.add(selectdifficuty);
        selectdifficuty.setBounds(224, 74, 247, 74);

        easy.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        easy.setForeground(new java.awt.Color(38, 121, 11));
        easy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easy.setText("EASY");
        easy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyMouseClicked(evt);
            }
        });
        selectpanel.add(easy);
        easy.setBounds(284, 166, 115, 61);

        medium.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        medium.setForeground(new java.awt.Color(248, 248, 59));
        medium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medium.setText("MEDIUM");
        medium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumMouseClicked(evt);
            }
        });
        selectpanel.add(medium);
        medium.setBounds(284, 245, 115, 61);

        hard.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        hard.setForeground(new java.awt.Color(244, 0, 0));
        hard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hard.setText("HARD");
        hard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardMouseClicked(evt);
            }
        });
        selectpanel.add(hard);
        hard.setBounds(284, 324, 115, 61);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4hKtCAo.jpg"))); // NOI18N
        selectpanel.add(jLabel6);
        jLabel6.setBounds(-300, -200, 1520, 1040);

        jPanel1.add(selectpanel, "card3");

        levelpanel.setPreferredSize(new java.awt.Dimension(829, 553));

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setForeground(new java.awt.Color(204, 153, 255));
        jPanel7.setLayout(null);

        lev1.setBackground(lev4.getBackground());
        lev1.setPreferredSize(new java.awt.Dimension(144, 144));
        lev1.setLayout(null);

        level1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level1.setForeground(new java.awt.Color(102, 102, 102));
        level1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level1.setText("1");
        level1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level1MouseClicked(evt);
            }
        });
        lev1.add(level1);
        level1.setBounds(0, 0, 144, 79);

        lock1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev1.add(lock1);
        lock1.setBounds(0, 0, 144, 144);

        levelstar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev1.add(levelstar1);
        levelstar1.setBounds(12, 86, 32, 32);

        levelstar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev1.add(levelstar2);
        levelstar2.setBounds(56, 99, 32, 32);

        levelstar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev1.add(levelstar3);
        levelstar3.setBounds(100, 86, 32, 36);

        jPanel7.add(lev1);
        lev1.setBounds(24, 129, 144, 144);

        lev2.setBackground(lev10.getBackground());
        lev2.setPreferredSize(new java.awt.Dimension(144, 144));
        lev2.setLayout(null);

        level2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level2.setForeground(new java.awt.Color(102, 102, 102));
        level2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level2.setText("2");
        level2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level2MouseClicked(evt);
            }
        });
        lev2.add(level2);
        level2.setBounds(0, 0, 144, 79);

        lock2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev2.add(lock2);
        lock2.setBounds(0, 0, 144, 144);

        levelstar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev2.add(levelstar4);
        levelstar4.setBounds(12, 86, 32, 32);

        levelstar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev2.add(levelstar5);
        levelstar5.setBounds(56, 99, 32, 32);

        levelstar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev2.add(levelstar6);
        levelstar6.setBounds(100, 86, 32, 36);

        jPanel7.add(lev2);
        lev2.setBounds(180, 129, 144, 144);

        lev3.setBackground(lev4.getBackground());
        lev3.setMinimumSize(new java.awt.Dimension(144, 144));
        lev3.setLayout(null);

        level3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level3.setForeground(new java.awt.Color(102, 102, 102));
        level3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level3.setText("3");
        level3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level3MouseClicked(evt);
            }
        });
        lev3.add(level3);
        level3.setBounds(0, 0, 144, 79);

        lock3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev3.add(lock3);
        lock3.setBounds(0, 0, 144, 144);

        levelstar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev3.add(levelstar7);
        levelstar7.setBounds(12, 86, 32, 32);

        levelstar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev3.add(levelstar8);
        levelstar8.setBounds(56, 99, 32, 32);

        levelstar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev3.add(levelstar9);
        levelstar9.setBounds(100, 86, 32, 36);

        jPanel7.add(lev3);
        lev3.setBounds(338, 129, 144, 144);

        lev4.setMinimumSize(new java.awt.Dimension(144, 144));
        lev4.setLayout(null);

        level4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level4.setText("4");
        level4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level4MouseClicked(evt);
            }
        });
        lev4.add(level4);
        level4.setBounds(0, 0, 144, 79);

        lock4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev4.add(lock4);
        lock4.setBounds(0, 0, 144, 144);

        levelstar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev4.add(levelstar10);
        levelstar10.setBounds(12, 86, 32, 32);

        levelstar11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev4.add(levelstar11);
        levelstar11.setBounds(56, 99, 32, 32);

        levelstar12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev4.add(levelstar12);
        levelstar12.setBounds(100, 86, 32, 36);

        jPanel7.add(lev4);
        lev4.setBounds(503, 129, 144, 144);

        lev5.setPreferredSize(new java.awt.Dimension(144, 144));
        lev5.setLayout(null);

        level5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level5.setText("5");
        level5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level5MouseClicked(evt);
            }
        });
        lev5.add(level5);
        level5.setBounds(0, 0, 144, 79);

        lock5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev5.add(lock5);
        lock5.setBounds(0, 0, 144, 144);

        levelstar13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev5.add(levelstar13);
        levelstar13.setBounds(12, 86, 32, 32);

        levelstar14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev5.add(levelstar14);
        levelstar14.setBounds(56, 99, 32, 32);

        levelstar15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev5.add(levelstar15);
        levelstar15.setBounds(100, 86, 32, 36);

        jPanel7.add(lev5);
        lev5.setBounds(666, 129, 144, 144);

        lev6.setMinimumSize(new java.awt.Dimension(144, 144));
        lev6.setLayout(null);

        level6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level6.setText("6");
        level6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level6MouseClicked(evt);
            }
        });
        lev6.add(level6);
        level6.setBounds(0, 0, 144, 79);

        lock6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev6.add(lock6);
        lock6.setBounds(0, 0, 144, 144);

        levelstar16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev6.add(levelstar16);
        levelstar16.setBounds(12, 86, 32, 32);

        levelstar17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev6.add(levelstar17);
        levelstar17.setBounds(56, 99, 32, 32);

        levelstar18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev6.add(levelstar18);
        levelstar18.setBounds(100, 86, 32, 36);

        jPanel7.add(lev6);
        lev6.setBounds(24, 336, 144, 144);

        lev7.setMinimumSize(new java.awt.Dimension(144, 144));
        lev7.setLayout(null);

        level7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level7.setText("7");
        level7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level7MouseClicked(evt);
            }
        });
        lev7.add(level7);
        level7.setBounds(0, 0, 144, 79);

        lock7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev7.add(lock7);
        lock7.setBounds(0, 0, 144, 144);

        levelstar19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev7.add(levelstar19);
        levelstar19.setBounds(12, 86, 32, 32);

        levelstar20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev7.add(levelstar20);
        levelstar20.setBounds(56, 99, 32, 32);

        levelstar21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev7.add(levelstar21);
        levelstar21.setBounds(100, 86, 32, 36);

        jPanel7.add(lev7);
        lev7.setBounds(180, 336, 144, 144);

        lev8.setPreferredSize(new java.awt.Dimension(144, 144));
        lev8.setLayout(null);

        level8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level8.setText("8");
        level8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level8MouseClicked(evt);
            }
        });
        lev8.add(level8);
        level8.setBounds(0, 0, 144, 79);

        lock8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev8.add(lock8);
        lock8.setBounds(0, 0, 144, 144);

        levelstar22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev8.add(levelstar22);
        levelstar22.setBounds(12, 86, 32, 32);

        levelstar23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev8.add(levelstar23);
        levelstar23.setBounds(56, 99, 32, 32);

        levelstar24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev8.add(levelstar24);
        levelstar24.setBounds(100, 86, 32, 36);

        jPanel7.add(lev8);
        lev8.setBounds(342, 336, 144, 144);

        lev9.setPreferredSize(new java.awt.Dimension(144, 144));
        lev9.setLayout(null);

        level9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        level9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level9.setText("9");
        level9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level9MouseClicked(evt);
            }
        });
        lev9.add(level9);
        level9.setBounds(0, 0, 144, 79);

        lock9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev9.add(lock9);
        lock9.setBounds(0, 0, 144, 144);

        levelstar25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev9.add(levelstar25);
        levelstar25.setBounds(12, 86, 32, 32);

        levelstar26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev9.add(levelstar26);
        levelstar26.setBounds(56, 99, 32, 32);

        levelstar27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev9.add(levelstar27);
        levelstar27.setBounds(100, 86, 32, 36);

        jPanel7.add(lev9);
        lev9.setBounds(504, 336, 144, 144);

        lev10.setPreferredSize(new java.awt.Dimension(144, 144));
        lev10.setLayout(null);

        level10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        level10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        level10.setText("10");
        level10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        level10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                level10MouseClicked(evt);
            }
        });
        lev10.add(level10);
        level10.setBounds(0, 0, 144, 79);

        lock10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lev10.add(lock10);
        lock10.setBounds(0, 0, 144, 144);

        levelstar28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev10.add(levelstar28);
        levelstar28.setBounds(12, 86, 32, 32);

        levelstar29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev10.add(levelstar29);
        levelstar29.setBounds(56, 99, 32, 32);

        levelstar30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (4).png"))); // NOI18N
        lev10.add(levelstar30);
        levelstar30.setBounds(100, 86, 32, 36);

        jPanel7.add(lev10);
        lev10.setBounds(666, 336, 144, 144);

        gotodifficultybtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gotodifficultybtn.setForeground(new java.awt.Color(255, 255, 255));
        gotodifficultybtn.setText("GO BACK");
        gotodifficultybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gotodifficultybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotodifficultybtnMouseClicked(evt);
            }
        });
        jPanel7.add(gotodifficultybtn);
        gotodifficultybtn.setBounds(20, 16, 140, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kode-lgx-one-with-the-sunzz1.jpg"))); // NOI18N
        jPanel7.add(jLabel5);
        jLabel5.setBounds(0, 0, 1070, 700);

        javax.swing.GroupLayout levelpanelLayout = new javax.swing.GroupLayout(levelpanel);
        levelpanel.setLayout(levelpanelLayout);
        levelpanelLayout.setHorizontalGroup(
            levelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        levelpanelLayout.setVerticalGroup(
            levelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        jPanel1.add(levelpanel, "card4");

        trickpanel.setLayout(new javax.swing.OverlayLayout(trickpanel));

        shadow.setPreferredSize(new java.awt.Dimension(829, 553));

        shadowinner.setLayout(new java.awt.CardLayout());

        trgobackbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trgobackbtn.setText("GO BACK");
        trgobackbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trgobackbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trgobackbtnMouseClicked(evt);
            }
        });

        trresumebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trresumebtn.setText("RESUME");
        trresumebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trresumebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trresumebtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pauseLayout = new javax.swing.GroupLayout(pause);
        pause.setLayout(pauseLayout);
        pauseLayout.setHorizontalGroup(
            pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pauseLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trgobackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(trresumebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        pauseLayout.setVerticalGroup(
            pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pauseLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trgobackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trresumebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        shadowinner.add(pause, "card2");

        trstatus.setBackground(new java.awt.Color(204, 204, 204));

        statustxt.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        statustxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnnextlevel.setText("NEXT LEVEL");
        btnnextlevel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnextlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextlevelActionPerformed(evt);
            }
        });

        btnretry.setText("RETRY");
        btnretry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnretry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trstatusLayout = new javax.swing.GroupLayout(trstatus);
        trstatus.setLayout(trstatusLayout);
        trstatusLayout.setHorizontalGroup(
            trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trstatusLayout.createSequentialGroup()
                .addGroup(trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trstatusLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(trstatusLayout.createSequentialGroup()
                                .addComponent(btnretry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnnextlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(trstatusLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(star1)
                        .addGap(18, 18, 18)
                        .addComponent(star2)
                        .addGap(18, 18, 18)
                        .addComponent(star3)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        trstatusLayout.setVerticalGroup(
            trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trstatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(star1)
                    .addGroup(trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(star2)
                        .addGroup(trstatusLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(star3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(trstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnextlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnretry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        shadowinner.add(trstatus, "card3");

        javax.swing.GroupLayout shadowLayout = new javax.swing.GroupLayout(shadow);
        shadow.setLayout(shadowLayout);
        shadowLayout.setHorizontalGroup(
            shadowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shadowLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(shadowinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        shadowLayout.setVerticalGroup(
            shadowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shadowLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(shadowinner, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        trickpanel.add(shadow);

        lastpanel.setPreferredSize(new java.awt.Dimension(829, 553));

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setLayout(null);

        hintlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hintlabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hintlabel.setText("HINT");
        hintlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hintlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hintlabelMouseClicked(evt);
            }
        });
        jPanel9.add(hintlabel);
        hintlabel.setBounds(511, 13, 267, 73);

        but1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        jPanel9.add(but1);
        but1.setBounds(51, 283, 75, 71);

        but2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        jPanel9.add(but2);
        but2.setBounds(144, 283, 75, 71);

        but3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        jPanel9.add(but3);
        but3.setBounds(226, 283, 75, 71);

        but4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        jPanel9.add(but4);
        but4.setBounds(313, 283, 75, 71);

        but5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });
        jPanel9.add(but5);
        but5.setBounds(400, 283, 75, 71);

        but6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });
        jPanel9.add(but6);
        but6.setBounds(487, 283, 75, 71);

        but7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });
        jPanel9.add(but7);
        but7.setBounds(574, 283, 75, 71);

        but8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });
        jPanel9.add(but8);
        but8.setBounds(667, 283, 75, 71);

        trieslabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        trieslabel.setText("No of tries: 3");
        jPanel9.add(trieslabel);
        trieslabel.setBounds(622, 475, 156, 41);

        lastpanelsabarkar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastpanelsabarkar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastpanelsabarkar.setText("PAUSE");
        lastpanelsabarkar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lastpanelsabarkar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastpanelsabarkarMouseClicked(evt);
            }
        });
        jPanel9.add(lastpanelsabarkar);
        lastpanelsabarkar.setBounds(18, 13, 110, 70);

        ch1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch1.setFocusable(false);
        ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1ActionPerformed(evt);
            }
        });
        jPanel9.add(ch1);
        ch1.setBounds(51, 198, 75, 78);

        ch2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch2.setFocusable(false);
        jPanel9.add(ch2);
        ch2.setBounds(144, 198, 75, 78);

        ch3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch3.setFocusable(false);
        jPanel9.add(ch3);
        ch3.setBounds(226, 198, 75, 78);

        ch4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch4.setFocusable(false);
        jPanel9.add(ch4);
        ch4.setBounds(313, 198, 75, 78);

        ch5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch5.setFocusable(false);
        jPanel9.add(ch5);
        ch5.setBounds(400, 198, 75, 78);

        ch6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch6.setFocusable(false);
        jPanel9.add(ch6);
        ch6.setBounds(487, 198, 75, 78);

        ch7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch7.setFocusable(false);
        jPanel9.add(ch7);
        ch7.setBounds(574, 198, 75, 78);

        ch8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch8.setFocusable(false);
        jPanel9.add(ch8);
        ch8.setBounds(667, 198, 75, 78);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ls_bkgd_color1.jpg"))); // NOI18N
        jPanel9.add(jLabel8);
        jLabel8.setBounds(-100, -10, 1070, 660);

        javax.swing.GroupLayout lastpanelLayout = new javax.swing.GroupLayout(lastpanel);
        lastpanel.setLayout(lastpanelLayout);
        lastpanelLayout.setHorizontalGroup(
            lastpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        lastpanelLayout.setVerticalGroup(
            lastpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        trickpanel.add(lastpanel);

        jPanel1.add(trickpanel, "card5");

        chalphutpanel.setPreferredSize(new java.awt.Dimension(829, 553));
        chalphutpanel.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 51, 255));
        jLabel1.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thank You For Playing ^_^");
        jLabel1.setOpaque(true);
        chalphutpanel.add(jLabel1);
        jLabel1.setBounds(199, 209, 431, 61);

        jLabel2.setBackground(new java.awt.Color(27, 119, 140));
        jLabel2.setFont(new java.awt.Font("Adobe Garamond Pro", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hope you Enjoyed !");
        jLabel2.setOpaque(true);
        chalphutpanel.add(jLabel2);
        jLabel2.setBounds(268, 302, 280, 56);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/856028.png"))); // NOI18N
        chalphutpanel.add(jLabel9);
        jLabel9.setBounds(0, 0, 910, 590);

        jPanel1.add(chalphutpanel, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void writeinitialstars(){
        try {
            Scanner read=new Scanner(scorefile);
                for(int i=0;i<10;i++){
                    read.next();String show=read.nextLine();show=show.trim();
                    Integer i1=new Integer(show);
                    numberofstars[i]=i1;
                }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    //new start
    public void checkgamestate(){
        try {
            File statefile=new File("src\\files\\gamestate.txt");
            Scanner readstate=new Scanner(statefile);
            readstate.next();String status=readstate.nextLine();status=status.trim();
            System.out.println("Status read is:"+status);
            if(status.equalsIgnoreCase("false")){
                resume.setEnabled(false);System.out.println("It is set to false");
            }
            else{
                resume.setEnabled(true);
            }
            Boolean b=new Boolean(status);
            gamestarted=b;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    //new end
//SELECT PANEL
    private void easyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseClicked
        //Changes
            selectpanel.setVisible(false);
            setDifficulty('e');
            //new start
            setFileDestination("src\\files\\easyLevelsscore.txt");
            writeinitialstars();
            //new end
            readdata();
            
            lockalllevel();
            unlocklevel();
            
            
            levelpanel.setVisible(true);
            System.out.println("CLicked meeee");
        //change end
        
        
    }//GEN-LAST:event_easyMouseClicked

    private void mediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumMouseClicked
            selectpanel.setVisible(false);
            setDifficulty('m');
            //new start
            setFileDestination("src\\files\\mediumLevelsscore.txt");
            writeinitialstars();
            //new end
            readdata();
            
            lockalllevel();
            unlocklevel();
            
            levelpanel.setVisible(true);
            System.out.println("CLicked meeee");
    }//GEN-LAST:event_mediumMouseClicked

    private void hardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseClicked
            selectpanel.setVisible(false);
            setDifficulty('h');
            //new start
            setFileDestination("src\\files\\hardLevelsscore.txt");
            writeinitialstars();
            //new end
            readdata();
            
            lockalllevel();
            unlocklevel();
            
            levelpanel.setVisible(true);
            System.out.println("CLicked meeee");
    }//GEN-LAST:event_hardMouseClicked
    public void setDifficulty(char difficulty) {
        this.difficultyoflevel=difficulty;
        
        Code_Levels.setDifficulty(difficulty);
    }

    public void readdata(){
        int start=0;
        try {
            Scanner read=new Scanner(scorefile);
            
            for(int i=0;i<10;i++){
                read.next();String show=read.nextLine();show=show.trim();
                Integer i1=new Integer(show);
                System.out.println("DIkha de jo bhej raha hai:"+i1);
                glowlevelstars(start,i1);
                //increament by 3
                start=start+3;
            }
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void declarelevelstars(){
        //Declare level stars
        mylevelstars[0]=levelstar1;mylevelstars[1]=levelstar2;mylevelstars[2]=levelstar3;mylevelstars[3]=levelstar4;mylevelstars[4]=levelstar5;mylevelstars[5]=levelstar6;mylevelstars[6]=levelstar7;mylevelstars[7]=levelstar8;mylevelstars[8]=levelstar9;mylevelstars[9]=levelstar10;
        mylevelstars[10]=levelstar11;mylevelstars[11]=levelstar12;mylevelstars[12]=levelstar13;mylevelstars[13]=levelstar14;mylevelstars[14]=levelstar15;mylevelstars[15]=levelstar16;mylevelstars[16]=levelstar17;mylevelstars[17]=levelstar18;mylevelstars[18]=levelstar19;mylevelstars[19]=levelstar20;
        mylevelstars[20]=levelstar21;mylevelstars[21]=levelstar22;mylevelstars[22]=levelstar23;mylevelstars[23]=levelstar24;mylevelstars[24]=levelstar25;mylevelstars[25]=levelstar26;mylevelstars[26]=levelstar27;mylevelstars[27]=levelstar28;mylevelstars[28]=levelstar29;mylevelstars[29]=levelstar30;
        //
    }
    public void declarelock(){
        locks[0]=lock1;locks[1]=lock2;locks[2]=lock3;locks[3]=lock4;locks[4]=lock5;locks[5]=lock6;locks[6]=lock7;
        locks[7]=lock8;locks[8]=lock9;locks[9]=lock10;
    
    
    }
    public void declarelevelpanel(){
    
        chotapanel[0]=lev1;chotapanel[1]=lev2;chotapanel[2]=lev3;chotapanel[3]=lev4;chotapanel[4]=lev5;chotapanel[5]=lev6;
        chotapanel[6]=lev7;chotapanel[7]=lev8;chotapanel[8]=lev9;chotapanel[9]=lev10;
    
    }
        ImageIcon icon12=new ImageIcon(MainPanel.class.getResource("/images/stardiamond.png"));
        
    public void glowlevelstars(int start,int end){
        
        System.out.println("start:"+start+" end:"+end);
       
        end=start+end;
        for(int i=start;i<end;i++){
            mylevelstars[i].setIcon(icon12);
            
        }
    }
    public void resetlevelstars(){
        ImageIcon i1=new ImageIcon(MainPanel.class.getResource("/images/star (4).png"));
    for (JLabel mylevelstar : mylevelstars) {
        mylevelstar.setIcon(i1);
    }
        
    }     public void settextfield(char[] charr){
        String s1=new String(charr);
        
        
    }
    ImageIcon lockimg=new ImageIcon("src\\images\\locked.png");
    public void lockalllevel(){
        for(int i=1;i<locks.length;i++){
            locks[i].setIcon(lockimg);
            chotapanel[i].setEnabled(false);
        }
    
    }
    public void unlocklevel(){
          try {
            Scanner read=new Scanner(scorefile);
            
            for(int i=0;i<10;i++){
                read.next();String show=read.nextLine();show=show.trim();
                Integer i1=new Integer(show);
                if(i==10){
                   
                }
                else if(i1==2 || i1==3){
                        locks[i+1].setIcon(null);
                        chotapanel[i+1].setEnabled(true);

                    }
                    
            }
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
     public void loadtextfield(char[] naklich){
        int j=0;
        Font font1 = new Font("Tahoma", Font.BOLD, 36);
        
        mytextfield[0]=ch1;
        mytextfield[1]=ch2;mytextfield[2]=ch3;mytextfield[3]=ch4;mytextfield[4]=ch5;mytextfield[5]=ch6;
        mytextfield[6]=ch7;mytextfield[7]=ch8;
        
        //Blank all text ke dabe
        for(int t=0;t<mytextfield.length;t++){
            mytextfield[t].setText("");
            mytextfield[t].setFocusable(false);
        
        }
        
        
        //Make invisible all text ke dabe
        for(int i=0;i<mytextfield.length;i++){
             mytextfield[i].setVisible(false);
             mytextfield[i].setFont(font1);
            }
        //Only visible those text daba which contain character
        if(naklich.length==3){
            setStartofwords(2);
            setEndofwords(startofwords);
           for(int i=2;i<naklich.length+2;i++){
                mytextfield[i].setVisible(true);
                mytextfield[i].setText(""+naklich[j]);
                j++;
                endofwords++;
            }
           
        }
        else if(naklich.length==4){
            setStartofwords(2);
            setEndofwords(startofwords);
           for(int i=2;i<naklich.length+2;i++){
                mytextfield[i].setVisible(true);
                mytextfield[i].setText(""+naklich[j]);
                j++;
                endofwords++;
            }
           
        }
        else if(naklich.length==5){
            setStartofwords(1);
            setEndofwords(endofwords);
           for(int i=1;i<naklich.length+1;i++){
                mytextfield[i].setVisible(true);
                mytextfield[i].setText(""+naklich[j]);
                j++;
                endofwords++;
            }
           
           
           
        }
        else if(naklich.length==6){
            setStartofwords(1);
            setEndofwords(startofwords);
           for(int i=1;i<naklich.length+1;i++){
                mytextfield[i].setVisible(true);
                mytextfield[i].setText(""+naklich[j]);
                j++;
                endofwords++;
            }  
          
        }
        else if(naklich.length==7){
            setStartofwords(1);
            setEndofwords(startofwords);
            for(int i=1;i<naklich.length+1;i++){
                mytextfield[i].setVisible(true);
                mytextfield[i].setText(""+naklich[j]);
                j++;
                endofwords++;
            }
        }
        else if(naklich.length==8){
            setStartofwords(0);
            setEndofwords(startofwords);
            for(int i=0;i<mytextfield.length;i++){
                mytextfield[i].setVisible(true);
                mytextfield[i].setText(""+naklich[i]);
                endofwords++;
            }
        }
        
       
    }
     public void setbuttext(Code_Levels refrencelevel){
         mybuttons[0]=but1;mybuttons[1]=but2;mybuttons[2]=but3;mybuttons[3]=but4;mybuttons[4]=but5;mybuttons[5]=but6;
         mybuttons[6]=but7;mybuttons[7]=but8;
         indexesofwords=refrencelevel.getIndexarraywords();
         
         indexes=refrencelevel.getIndexes();
         //Put random char on buttons from E to
         int j=0;char randomchar='E';
         for(int a=0;a<mybuttons.length;a++){
             mybuttons[a].setText(""+randomchar);
             randomchar++;
         }
         
         int initial=2;
         for(int i=2;i<indexesofwords.length+initial;i++){
             mybuttons[i].setText(""+indexesofwords[j]);
             j++;
         }
         
         
         
         
     }

     


//LAST PANEL
    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
//        boolean b=false; 
//        b=levelrefrence.setcharacter(but1.getText().charAt(0));
//       if(b==true){
//           showMessageDialog(null, "Congratulations you have passed this level move onto next level");
//       }
        Wordchecker(but1.getText().charAt(0));
    }//GEN-LAST:event_but1ActionPerformed

    private void hintlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hintlabelMouseClicked
        
        if(hintcount<indexesofwords.length){
            
            System.out.println(indexesofwords[hintcount]);
            hintlabel.setText("HINT:"+indexesofwords[hintcount]);
            
            
            hintcount++;
            System.out.println("Hint count:"+hintcount);
        }
        else{
            hintlabel.setForeground(Color.red);
            hintlabel.setText("No more hints");
        }
        
    }//GEN-LAST:event_hintlabelMouseClicked

    private void lastpanelsabarkarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastpanelsabarkarMouseClicked

//go back ka code hai bad mai set kar
//        lastpanel.setVisible(false);
//        levelpanel.setVisible(true);

    shadow.setVisible(true);
    but1.setVisible(false);but2.setVisible(false);but3.setVisible(false);but4.setVisible(false);
     but8.setVisible(false);but7.setVisible(false);but6.setVisible(false);but5.setVisible(false);

//     but9.setVisible(false);but10.setVisible(false);but11.setVisible(false);but12.setVisible(false);
//     but13.setVisible(false);but14.setVisible(false);but15.setVisible(false);but16.setVisible(false);
//   
    }//GEN-LAST:event_lastpanelsabarkarMouseClicked

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
        Wordchecker(but8.getText().charAt(0));
    }//GEN-LAST:event_but8ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
        Wordchecker(but7.getText().charAt(0));
    }//GEN-LAST:event_but7ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
        Wordchecker(but6.getText().charAt(0));
    }//GEN-LAST:event_but6ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
        Wordchecker(but5.getText().charAt(0));
    }//GEN-LAST:event_but5ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        Wordchecker(but4.getText().charAt(0));
    }//GEN-LAST:event_but4ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        Wordchecker(but3.getText().charAt(0));
    }//GEN-LAST:event_but3ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        Wordchecker(but2.getText().charAt(0));
    }//GEN-LAST:event_but2ActionPerformed

    private void ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch1ActionPerformed

    private void trgobackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trgobackbtnMouseClicked
        //put go back code from there
        trickpanel.setVisible(false);origsettings();
        readdata();//To make stars glow
        
        lockalllevel();
        unlocklevel();
        
        levelpanel.setVisible(true);

        

    }//GEN-LAST:event_trgobackbtnMouseClicked

    private void origsettings(){
        shadow.setVisible(false);
     for(int i=0;i<8;i++){
        mybuttons[i].setVisible(true);
        mytextfield[i].setVisible(true);
     }   
    }
    private void shadowsettings(){
    
    for(int i=0;i<8;i++){
        mybuttons[i].setVisible(false);
        mytextfield[i].setVisible(false);
    }
    
    }
    private void trresumebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trresumebtnMouseClicked
        shadow.setVisible(false);
        but1.setVisible(true);but2.setVisible(true);but3.setVisible(true);but4.setVisible(true);
        but8.setVisible(true);but7.setVisible(true);but6.setVisible(true);but5.setVisible(true);

    }//GEN-LAST:event_trresumebtnMouseClicked

    private void btnnextlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextlevelActionPerformed
        pause.setVisible(true);trstatus.setVisible(false);origsettings();
        revertglowstars();
        nextLevel();
    }//GEN-LAST:event_btnnextlevelActionPerformed

    private void btnretryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretryActionPerformed
        pause.setVisible(true);trstatus.setVisible(false);origsettings();
        revertglowstars();
        retryLevel();
    }//GEN-LAST:event_btnretryActionPerformed

    private void startComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_startComponentAdded
        getContentPane().setBackground(Color.RED);

    }//GEN-LAST:event_startComponentAdded

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void newgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newgameMouseClicked
        //false to apna kam karo
        if(gamestarted==false){
            start.setVisible(false);
            selectpanel.setVisible(true);
            //to write in file
            setGameStarted(true);
        }
        else{
            int YesorNo=JOptionPane.showConfirmDialog(null,"Do you really want to start a new game?","Confirmation",JOptionPane.YES_NO_OPTION);
            //0 matlab yes
            if(YesorNo==0){
                
                    try{
                        //for easy
                        File temp1=new File("src\\files\\easyLevelsscore.txt");
                        PrintStream write=new PrintStream(temp1);

                        for(int i=0;i<10;i++){
                        write.println("Level"+(i+1)+": "+0);
                        }
                        //for medium
                        File temp2=new File("src\\files\\mediumLevelsscore.txt");
                        PrintStream write1=new PrintStream(temp2);

                        for(int i=0;i<10;i++){
                        write1.println("Level"+(i+1)+": "+0);
                        }
                        //for hard
                        File temp3=new File("src\\files\\hardLevelsscore.txt");
                        PrintStream write2=new PrintStream(temp3);

                        for(int i=0;i<10;i++){
                        write2.println("Level"+(i+1)+": "+0);
                        }
                        
                    }
                    
                    catch(Exception e){
                    
                    }
                    start.setVisible(false);
                    selectpanel.setVisible(true);
        
            }
            else{
            
            }
        }
        

    }//GEN-LAST:event_newgameMouseClicked

    private void level1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level1MouseClicked
        
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(0);

        Code_Levels l1=new Code_Levels(0);
        levelrefrence=l1;
        settextfield(l1.getNaklich());

        loadtextfield(l1.getNaklich());
        setbuttext(l1);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        //        levels.setVisible(true);
        //        levelmenu.setVisible(false);
        
    }//GEN-LAST:event_level1MouseClicked

    private void level2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level2MouseClicked
        if(lev2.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(1);

        Code_Levels l2=new Code_Levels(1);
        levelrefrence=l2;
        settextfield(l2.getNaklich());

        loadtextfield(l2.getNaklich());
        setbuttext(l2);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level2MouseClicked

    private void level3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level3MouseClicked
        if(lev3.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(2);

        Code_Levels l3=new Code_Levels(2);
        levelrefrence=l3;
        settextfield(l3.getNaklich());

        loadtextfield(l3.getNaklich());
        setbuttext(l3);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level3MouseClicked

    private void level4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level4MouseClicked
        if(lev4.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(3);

        Code_Levels l4=new Code_Levels(3);
        levelrefrence=l4;
        settextfield(l4.getNaklich());

        loadtextfield(l4.getNaklich());
        setbuttext(l4);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level4MouseClicked

    private void level5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level5MouseClicked
        if(lev5.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(4);

        Code_Levels l5=new Code_Levels(4);
        levelrefrence=l5;
        settextfield(l5.getNaklich());

        loadtextfield(l5.getNaklich());
        setbuttext(l5);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level5MouseClicked

    private void level6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level6MouseClicked
        if(lev6.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(5);

        Code_Levels l6=new Code_Levels(5);
        levelrefrence=l6;
        settextfield(l6.getNaklich());

        loadtextfield(l6.getNaklich());
        setbuttext(l6);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level6MouseClicked

    private void level7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level7MouseClicked
        if(lev7.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(6);

        Code_Levels l7=new Code_Levels(6);
        levelrefrence=l7;
        settextfield(l7.getNaklich());

        loadtextfield(l7.getNaklich());
        setbuttext(l7);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level7MouseClicked

    private void level8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level8MouseClicked
        if(lev8.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(7);

        Code_Levels l8=new Code_Levels(7);
        levelrefrence=l8;
        settextfield(l8.getNaklich());

        loadtextfield(l8.getNaklich());
        setbuttext(l8);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level8MouseClicked

    private void level9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level9MouseClicked
        if(lev9.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(8);

        Code_Levels l9=new Code_Levels(8);
        levelrefrence=l9;
        settextfield(l9.getNaklich());

        loadtextfield(l9.getNaklich());
        setbuttext(l9);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level9MouseClicked

    private void level10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level10MouseClicked
        if(lev10.isEnabled()){
        levelpanel.setVisible(false);trickpanel.setVisible(true);
        lastpanel.setVisible(true);
        setCurrentlevelno(9);

        Code_Levels l10=new Code_Levels(9);
        levelrefrence=l10;
        settextfield(l10.getNaklich());

        loadtextfield(l10.getNaklich());
        setbuttext(l10);
        this.origch=levelrefrence.getOrigch();
        this.origstring=levelrefrence.getOrigstring();
        setNumberoftries(3);numberofstars[currentlevelno]=3;
        setHintcount(0);hintlabel.setText("HINT");resetlevelstars();
        }
        else{}
    }//GEN-LAST:event_level10MouseClicked

    private void resumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumeMouseClicked
        if(resume.isEnabled()){
            start.setVisible(false);
            selectpanel.setVisible(true);
        }
        else{}
        
        
        
    }//GEN-LAST:event_resumeMouseClicked

    private void gotodifficultybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotodifficultybtnMouseClicked

        levelpanel.setVisible(false);
        //new1start
        resetlevelstars();
        //new1start
        selectpanel.setVisible(true);
        
    }//GEN-LAST:event_gotodifficultybtnMouseClicked
    public void Wordchecker(char c){
        
          
        int flag=0;
        for(int i=0;i<indexes.size();i++){
            if(c==origch[indexes.get(i)]){
                
                mytextfield[indexes.remove(i)+startofwords].setText(""+c);;
                flag++;
                break;
            }
                
        }
        if(flag==0){
            showMessageDialog(null, "Wrong character entered","Alert",JOptionPane.WARNING_MESSAGE);
            numberoftries--;numberofstars[currentlevelno]--;
            setTrieslabel();
        }
        if(numberoftries==0){
            showMessageDialog(null, "GAME OVER","ALERT",JOptionPane.OK_OPTION);
            writedata();origsettings();readdata();
            trickpanel.setVisible(false);lastpanel.setVisible(false);
            
            lockalllevel();unlocklevel();
            
            levelpanel.setVisible(true);
        }
        String checkerstring="";
        for(int i=0;i<mytextfield.length;i++){
            checkerstring=checkerstring+mytextfield[i].getText();
            
        }
        System.out.println(checkerstring);
        if(origstring.equals(checkerstring)){
            
//            showMessageDialog(null, "Riddle is solved No of stars obtained:"+numberofstars[currentlevelno],"GUESS THE WORD",JOptionPane.YES_NO_CANCEL_OPTION);
            
            if(numberofstars[currentlevelno]==1){
                statustxt.setText("Failed");statustxt.setHorizontalTextPosition(statustxt.CENTER);
            }
            else{
            statustxt.setText("Congratulations");statustxt.setHorizontalTextPosition(statustxt.CENTER);
            }
            
            
            shadow.setVisible(true);pause.setVisible(false);trstatus.setVisible(true);chknextlvlbtn(numberofstars[currentlevelno]);
            shadowsettings();glowstars();writedata();
            
//            nextLevel();
//            

        }
        
    }
    public void glowstars(){
        ImageIcon i1=new ImageIcon(MainPanel.class.getResource("/images/starfilled.png"));
        //Declare stars
        mystars[0]=star1;mystars[1]=star2;mystars[2]=star3;
        for(int i=0;i<numberofstars[currentlevelno];i++){
            mystars[i].setIcon(i1);
        
        }
    }
    public void revertglowstars(){
        ImageIcon i1=new ImageIcon(MainPanel.class.getResource("/images/star (1).png"));
        for(int i=0;i<3;i++){
            mystars[i].setIcon(i1);
        }
    
    
    }
    
    public void chknextlvlbtn(int stars){
        if(stars==2 || stars==3){
            btnnextlevel.setEnabled(true);
        }
        else{
            btnnextlevel.setEnabled(false);
        }
        
        
    }
    
    
    public void writedata(){
        
        try {
            PrintStream write=new PrintStream(scorefile);
            
            for(int i=0;i<10;i++){
            write.println("Level"+(i+1)+": "+numberofstars[i]);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }    
    
    
    public void nextLevel(){
        if(currentlevelno<9){
            currentlevelno++;
            setCurrentlevelno(currentlevelno);
        
            Code_Levels nextlevel=new Code_Levels(currentlevelno);
            levelrefrence=nextlevel;
            settextfield(nextlevel.getNaklich());

            loadtextfield(nextlevel.getNaklich());
            setbuttext(nextlevel);
            this.origch=levelrefrence.getOrigch();
            this.origstring=levelrefrence.getOrigstring();
            setNumberoftries(3);numberofstars[currentlevelno]=3;
            setHintcount(0);hintlabel.setText("HINT");
        
        }
        else{
            trickpanel.setVisible(false);lastpanel.setVisible(false);
            chalphutpanel.setVisible(true);
            
        }
     
    }
    public void retryLevel(){
        
            
            Code_Levels samelevel=new Code_Levels(currentlevelno);
            levelrefrence=samelevel;
            settextfield(samelevel.getNaklich());

            loadtextfield(samelevel.getNaklich());
            setbuttext(samelevel);
            this.origch=levelrefrence.getOrigch();
            this.origstring=levelrefrence.getOrigstring();
            setNumberoftries(3);numberofstars[currentlevelno]=3;
            setHintcount(0);hintlabel.setText("HINT");
        
        
            
            
        
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }
   
    
    
    
   
    Code_Levels levelrefrence;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnextlevel;
    private javax.swing.JButton btnretry;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JTextField ch1;
    private javax.swing.JTextField ch2;
    private javax.swing.JTextField ch3;
    private javax.swing.JTextField ch4;
    private javax.swing.JTextField ch5;
    private javax.swing.JTextField ch6;
    private javax.swing.JTextField ch7;
    private javax.swing.JTextField ch8;
    private javax.swing.JPanel chalphutpanel;
    private javax.swing.JLabel easy;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel gotodifficultybtn;
    private javax.swing.JLabel hard;
    private javax.swing.JLabel hintlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel lastpanel;
    private javax.swing.JLabel lastpanelsabarkar;
    private javax.swing.JPanel lev1;
    private javax.swing.JPanel lev10;
    private javax.swing.JPanel lev2;
    private javax.swing.JPanel lev3;
    private javax.swing.JPanel lev4;
    private javax.swing.JPanel lev5;
    private javax.swing.JPanel lev6;
    private javax.swing.JPanel lev7;
    private javax.swing.JPanel lev8;
    private javax.swing.JPanel lev9;
    private javax.swing.JLabel level1;
    private javax.swing.JLabel level10;
    private javax.swing.JLabel level2;
    private javax.swing.JLabel level3;
    private javax.swing.JLabel level4;
    private javax.swing.JLabel level5;
    private javax.swing.JLabel level6;
    private javax.swing.JLabel level7;
    private javax.swing.JLabel level8;
    private javax.swing.JLabel level9;
    private javax.swing.JPanel levelpanel;
    private javax.swing.JLabel levelstar1;
    private javax.swing.JLabel levelstar10;
    private javax.swing.JLabel levelstar11;
    private javax.swing.JLabel levelstar12;
    private javax.swing.JLabel levelstar13;
    private javax.swing.JLabel levelstar14;
    private javax.swing.JLabel levelstar15;
    private javax.swing.JLabel levelstar16;
    private javax.swing.JLabel levelstar17;
    private javax.swing.JLabel levelstar18;
    private javax.swing.JLabel levelstar19;
    private javax.swing.JLabel levelstar2;
    private javax.swing.JLabel levelstar20;
    private javax.swing.JLabel levelstar21;
    private javax.swing.JLabel levelstar22;
    private javax.swing.JLabel levelstar23;
    private javax.swing.JLabel levelstar24;
    private javax.swing.JLabel levelstar25;
    private javax.swing.JLabel levelstar26;
    private javax.swing.JLabel levelstar27;
    private javax.swing.JLabel levelstar28;
    private javax.swing.JLabel levelstar29;
    private javax.swing.JLabel levelstar3;
    private javax.swing.JLabel levelstar30;
    private javax.swing.JLabel levelstar4;
    private javax.swing.JLabel levelstar5;
    private javax.swing.JLabel levelstar6;
    private javax.swing.JLabel levelstar7;
    private javax.swing.JLabel levelstar8;
    private javax.swing.JLabel levelstar9;
    private javax.swing.JLabel lock1;
    private javax.swing.JLabel lock10;
    private javax.swing.JLabel lock2;
    private javax.swing.JLabel lock3;
    private javax.swing.JLabel lock4;
    private javax.swing.JLabel lock5;
    private javax.swing.JLabel lock6;
    private javax.swing.JLabel lock7;
    private javax.swing.JLabel lock8;
    private javax.swing.JLabel lock9;
    private javax.swing.JLabel medium;
    private javax.swing.JLabel newgame;
    private javax.swing.JLabel options;
    private javax.swing.JPanel pause;
    private javax.swing.JLabel resume;
    private javax.swing.JLabel selectdifficuty;
    private javax.swing.JPanel selectpanel;
    private javax.swing.JPanel shadow;
    private javax.swing.JPanel shadowinner;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JPanel start;
    private javax.swing.JLabel statustxt;
    private javax.swing.JLabel trgobackbtn;
    private javax.swing.JPanel trickpanel;
    private javax.swing.JLabel trieslabel;
    private javax.swing.JLabel trresumebtn;
    private javax.swing.JPanel trstatus;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    public int getCurrentlevelno() {
        return currentlevelno;
    }

    /**
     *
     */
    public void setCurrentlevelno(int currentlevelno) {
        this.currentlevelno = currentlevelno;
    }

    
    public int getStartofwords() {
        return startofwords;
    }

    
    public void setStartofwords(int startofwords) {
        this.startofwords = startofwords;
    }

    
    public void setNumberoftries(int numberoftries) {
        this.numberoftries = numberoftries;
        setTrieslabel();
    }

    
    public void setTrieslabel() {
        trieslabel.setText("No of tries: "+numberoftries);
    }

    

    
    public void setEndofwords(int endofwords) {
        this.endofwords = endofwords;
    }

    
    public int[] getNumberofstars() {
        return numberofstars;
    }

    
    public void setNumberofstars(int[] numberofstars) {
        this.numberofstars = numberofstars;
    }

    
    public void setHintcount(int hintcount) {
        this.hintcount = hintcount;
    }
    //new start
    public void setFileDestination(String location){
        destination=location;
        scorefile=new File(destination);
    }
    public void setGameStarted(boolean b){
        File ff=new File("src\\files\\gamestate.txt");
        try {
            PrintStream pp=new PrintStream(ff);
            pp.print("gamestate: ");pp.println(b);
            

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    //new end
    
    
}
